version: "3.9"
services:
  github-transfer-bot:
    image: registry.bgfamily.ca/github-transfer-bot:latest
    container_name: github-transfer-bot
    restart: unless-stopped
    environment:
        DISCORD_TOKEN: ${DISCORD_TOKEN}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        CLIENT_ID: ${CLIENT_ID}
        DATA_DIR: /opt/appdata
    volumes:
      - appdata:/opt/appdata

volumes:
  appdata: