on:
    release:
        types: [published]

jobs:
    deploy-to-rpi:
        runs-on: [self-hosted, linux, arm64]
        steps:
            - name: Checkout code
              run: |
                cd /home/ubuntu/github-transfer-bot
                git pull
            - name: Install packages
              run: |
                cd /home/ubuntu/github-transfer-bot
                npm i
            - name: Build new version
              run: |
                cd /home/ubuntu/github-transfer-bot
                npm run build
            - name: Restart bot
              run: |
                sudo systemctl stop issuemover
                sudo systemctl start issuemover